### ISSUE TITLE
Various build improvements with new TypeScript tooling

### ISSUE THREAD

**Issue by MikkCZ** [MikkCZ/pontoon-addon#135]
- [x] merge all to a single webpack/eslint/jest run and produce a single `main.js` file for all frontend pages -> #189
- [ ] include source maps into the production build, but consider the final extensions bundle size #192
- [ ] build manifest.json via webpack to get rid of `jq` dependency (https://www.npmjs.com/package/generate-json-webpack-plugin, https://stackoverflow.com/questions/44232366/how-do-i-build-a-json-file-with-webpack) #192
- [x] run tests and build independently
- [x] explicit type checking step (`tsc`) -> #189
- [x] unify `make` and `yarn` invocations -> #154
- [x] remove unused dependencies (lerna, sinon, ...) -> #189
- [x] use faster `shallow` where `mount` is not needed -> #120
