### ISSUE TITLE
Consolidate privacy policy to a single place

### ISSUE THREAD

**Issue by MikkCZ** [MikkCZ/pontoon-addon#146]
The privacy policy should be included in the extension itself, without going to any page. At the same time the text should be kept at as few places as possible, and have a single source of truth. For that reason I propose to:
- [x] #148 Move the privacy policy from wiki to the repository, as a Markdown file, so it's readable in the GitHub interface.
- [x] #150 Create a page in the extensions (point links internally there), which would render the Markdown file using e.g. [`marked`](https://www.npmjs.com/package/marked), with proper sanitization of the output of course. Looking at [intro](https://github.com/MikkCZ/pontoon-addon/tree/master/src/packages/intro) or [snake](https://github.com/MikkCZ/pontoon-addon/tree/master/src/packages/snake) is a good start how to create such page.
- [ ] #151 Using `marked`, generate a HTML version of the privacy policy to build artifacts, so it can be copied to AMO manually, but stil easily.
- [x] Change all links to point to the new file in the repository instead of wiki. In code and add-on stores. Put the new link into the original document, but remove it from the wiki navigation, in case someone still ends up there.

**Comment by flodolo** [comment]
Approach sounds great to me, and +1 on keeping the source of truth in one place.

**Comment by mathjazz** [comment]
LGTM.

Maybe first and last bullet point should be addressed first, others can follow later.

**Comment by MikkCZ** [comment]
I am looking into embedding the privacy policy directly into the extension.
